### ISSUE TITLE
efi_bgrt: Ignoring BGRT: invalid image address on Linux

### ISSUE THREAD

**Issue by godvino** [Jamesits/BGRTInjector#2]
I installed this EFI driver on my system by placing it into my `EFI/systemd/drivers` directory on my EFI partition and it is loaded by `systemd-boot` on boot. However no image is shown on startup. Relevant output from `dmesg`:
```
Oct 13 18:24:44 fedora kernel: efi: EFI v2.00 by INSYDE Corp.
Oct 13 18:24:44 fedora kernel: efi: ACPI=0x96ffe000 ACPI 2.0=0x96ffe014 SMBIOS=0x96e72d18 
Oct 13 18:24:44 fedora kernel: efi_bgrt: Ignoring BGRT: invalid image address
```
This message seems to be introduced to the Linux kernel by [this](https://github.com/torvalds/linux/commit/792ef14df5c585c19b2831673a077504a09e5203) commit.

Note that my system doen't support BGRT ootb but I think this driver could fix that.

I have built the driver as a "EFI boot service driver" by changing the SUBSYSTEM in the Makefile since that seems to be required by systemd-boot.

**Comment by godvino** [comment]
It does work properly on Windows though.

**Comment by Jamesits** [comment]
[BGRTInjector.zip](https://github.com/Jamesits/BGRTInjector/files/9781205/BGRTInjector.zip)

Try this one? Compiled on cb48567cff707ce74d3a07b17ee09c25e75b9ad0

**Comment by Jamesits** [comment]
> I have built the driver as a "EFI boot service driver" by changing the SUBSYSTEM in the Makefile since that seems to be required by systemd-boot.

Hmm didn't consider that; actually I have no idea if the Makefile works before. :D

Try compile da4e33767df13f402380c6ea615e02f3ceb19196 and see if it works for you.

**Comment by godvino** [comment]
Yep latest `master` works fine now. Thanks a lot for your work.
Btw is there any reason why you defined `LOAD_WINDOWS` by default ? I had to undefine that in order to not get into a bootloop.

**Comment by Jamesits** [comment]
You made a very good point. Flag `LOAD_WINDOWS` is disabled by default now. 

At the time of writing I'm not aware of Linux support for BGRT, so everything is tested only on Windows...
